#+TITLE: License Information
#+AUTHOR: aygp-dr
#+DATE: 2025-03-16
#+PROPERTY: header-args :mkdirp yes

* MIT License

Copyright (c) 2024-2025 aygp-dr

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

* Dependencies and Licenses

para-spacy-lisp uses several open-source libraries, each with their own licenses:

** Python Dependencies

| Package    | License      | Website                          |
|------------+--------------+----------------------------------|
| spaCy      | MIT          | https://spacy.io                 |
| websockets | BSD 3-Clause | https://websockets.readthedocs.io |
| pydantic   | MIT          | https://pydantic-docs.helpmanual.io |
| click      | BSD 3-Clause | https://click.palletsprojects.com  |

** Emacs Dependencies

| Package     | License | Website                               |
|-------------+---------+---------------------------------------|
| websocket.el | GPL-3.0 | https://github.com/ahyatt/emacs-websocket |
| json.el     | GPL-3.0 | Built into Emacs                      |

* License Compliance

To ensure license compliance:

1. All modifications to the software should maintain the existing license headers
2. Any new files should include the appropriate license header
3. Third-party code should be clearly marked with its original license
4. Contributions are accepted under the project's license

* License Text

The full text of the MIT License is available in the LICENSE file at the root of this project.